[tool.poetry]
name = "simplex-assimilate"
version = "0.2.7"
description = "Perform Data Assimilation on the Simplex. Models an ensemble as a mixture of Dirichlet distributions."
authors = ["Oscar Laird <olaird25@gmail.com>"]
readme = "README.md"
packages = [{include = "simplex_assimilate"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
numpy = "^1.24.3"
scipy = "^1.10.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
anybadge = "^1.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
