[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "id-connect-package-packagingCon23"
version = "0.0.4"
description = "id-connect-package-packagingCon23"
readme = "README.md"
