[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lang_support"
version = "1.3.0"
authors = [
  { name="Mateusz Ferenc", email="ferenc.mateusz.priv@gmail.com" },
]
maintainers = [
  { name="Mateusz Ferenc", email="ferenc.mateusz.priv@gmail.com" },
]
description = "Package that provides an easy API for adding different, easily changeable languages."
keywords = [ "multilangual", "language change", "language", "languages" ]
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "simpldlogger>=1.3.0",
]

[project.urls]
"Homepage" = "https://github.com/MateuszFerenc/my_pythons/tree/main/lang_support"
"Bug Tracker" = "https://github.com/mateuszferenc/my_pythons/issues"