[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "simpldlogger"
version = "1.3.0"
authors = [
  { name="Mateusz Ferenc", email="ferenc.mateusz.priv@gmail.com" },
]
maintainers = [
  { name="Mateusz Ferenc", email="ferenc.mateusz.priv@gmail.com" },
]
description = "Package that provides an easy API for logging different types of events that have occurred."
keywords = [ "logging", "data logger" ]
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/MateuszFerenc/my_pythons/tree/main/data_logger"
"Bug Tracker" = "https://github.com/MateuszFerenc/my_pythons/issues"