[project]
name = "merchant001_sdk"
description = ""
authors = [
    { name = "Alexander Lavrov", email = "alexander.lavrov@elastoo.com" },
]
dependencies = [
    "httpx>=0.24.0",
]
requires-python = ">=3.10,<=3.12"
dynamic = []
readme = "README.md"
keywords = [
    "CLI",
    "client",
    "convertation",
    "crypto",
    "usdt",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Other Environment",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
version = "0.0.20"

[project.license]
file = "LICENSE"

[project.scripts]
merchant001-sdk = "merchant001_sdk.__main__:start"

[project.urls]
repository = "https://github.com/Elastoo-Team/merchant001_sdk"
documentation = "https://merchant001_sdk.readthedocs.io"

[project.optional-dependencies]
cli = [
    "cliar>=1.3.5",
]

[tool.pdm.version]
source = "file"
path = "merchant001_sdk/__about__.py"

[tool.pdm.dev-dependencies]
dev = [
    "ipython==8.4.0",
    "pre-commit==2.20.0",
    "interrogate==1.5.0",
    "doq==0.9.1",
    "commitizen==2.31.0",
    "ipykernel==6.17.1",
    "mkdocs==1.4.1",
    "mkdocs-material==8.5.10",
    "mkdocstrings[python]==0.19.0",
]

[tool.pdm.build]
includes = []

[tool.pdm.scripts]
add = "git add ."
lint = "pre-commit run -a"

[tool.pdm.scripts.all]
composite = [
    "add",
    "lint",
]

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 70
exclude = [
    "setup.py",
    "docs",
    "build",
]
ignore-regex = [
    "^get$",
    "^mock_.*",
    ".*BaseClass.*",
]
verbose = 0
quiet = false
whitelist-regex = []
color = true
omit-covered-files = false

[tool.black]
line-length = 120
include = "\\.pyi?$"
target-version = [
    "py311",
]
exclude = "(\n  /(\n      \\.eggs         # exclude a few common directories in the\n    | \\.git          # root of the project\n    | \\.hg\n    | \\.mypy_cache\n    | \\.tox\n    | \\.venv\n    | _build\n    | buck-out\n    | build\n    | dist\n    | migrations\n  )\n)\n"

[tool.isort]
known_first_party = "merchant001_sdk"
line_length = 120
profile = "black"
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true

[tool.pycln]
all = true

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
no_site_packages = true
strict_optional = false
strict = true
allow_subclassing_any = true
allow_untyped_calls = true
pretty = true
show_error_codes = true
implicit_reexport = true
allow_untyped_decorators = true
warn_return_any = false
disable_error_code = [
    "valid-type",
    "call-arg",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.20"
version_files = [
    "merchant001_sdk/__about__.py:__version__",
]
style = [
    [
        "qmark",
        "fg:#ff9d00 bold",
    ],
    [
        "question",
        "bold",
    ],
    [
        "answer",
        "fg:#ff9d00 bold",
    ],
    [
        "pointer",
        "fg:#ff9d00 bold",
    ],
    [
        "highlighted",
        "fg:#ff9d00 bold",
    ],
    [
        "selected",
        "fg:#cc5454",
    ],
    [
        "separator",
        "fg:#cc5454",
    ],
    [
        "instruction",
        "",
    ],
    [
        "text",
        "",
    ],
    [
        "disabled",
        "fg:#858585 italic",
    ],
]

[build-system]
requires = [
    "pdm-pep517==1.0.4",
]
build-backend = "pdm.pep517.api"
