[tool.poetry]
name = "brucityslots"
version = "0.1.2"
description = ""
authors = [
    "Lukas Valatka <lukas.valatka123@gmail.com>",
]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^2.3"
requests = "^2.28.1"
python-dateutil = "^2.8"

[tool.poetry.dev-dependencies]
pre-commit = "^3.4.0"
ruff = "^0.0.292"

[tool.poetry.scripts]
brucityslots = "brucityslots.app:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
